steps:
  - name: docker-build-pr
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: andrewgosselin/portfolio
      dockerfile: Dockerfile
      context: .
      dry_run: true
      build_args:
        - PHP_EXT_JOBS=2
      cache_from:
        - andrewgosselin/portfolio:buildcache
      cache_to:
        - type=registry,ref=andrewgosselin/portfolio:buildcache,mode=max
    when:
      event:
        - pull_request

  - name: docker-publish
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: andrewgosselin/portfolio
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      tags:
        - latest
        - ${CI_COMMIT_SHA}
      auto_tag: true
      build_args:
        - PHP_EXT_JOBS=2
      cache_from:
        - andrewgosselin/portfolio:buildcache
      cache_to:
        - type=registry,ref=andrewgosselin/portfolio:buildcache,mode=max
    when:
      event:
        - push
      branch:
        - master

  - name: docker-publish-tag
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: andrewgosselin/portfolio
      dockerfile: Dockerfile
      context: .
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_token
      auto_tag: true
      build_args:
        - PHP_EXT_JOBS=2
      cache_from:
        - andrewgosselin/portfolio:buildcache
      cache_to:
        - type=registry,ref=andrewgosselin/portfolio:buildcache,mode=max
    when:
      event:
        - tag
